[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
]
copyleft = "allow"

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
    # Winit
    { name = "winapi", version = "0.2.8" }, # winit -> mio-extras -> mio requires this
    # graphics
    { name = "core-foundation", version = "0.7.0" }, # winit uses old version
    { name = "core-foundation-sys", version = "0.7.0" }, # winit uses old version
    # parking_lot
    { name = "parking_lot", version = "0.10" },
    { name = "parking_lot_core", version = "0.7.2" },
    { name = "lock_api", version = "0.3.4" },
    { name = "cloudabi", version = "0.0.3" },
    # hecs & lru
    { name = "hashbrown", version = "0.8.2" },
    # wasi
    { name = "wasi", version = "0.9.0+wasi-snapshot-preview1" },
    # ddsfile
    { name = "num-traits", version = "0.1.43" }
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
    "RUSTSEC-2020-0016"  # async-std is using net2 which id deprecated in favor of socket2
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
